### ISSUE TITLE
сделать объект game

### ISSUE THREAD

**Issue by studio-webcamp** [studio-webcamp/ezenglish#1]
в объекте game 
свойства и методы 
start, 
answer, 
player, 
questions, 
match
getAnswer
match
getAnswer
функцию Person не трогать

**Comment by Bogdan92** [comment]
Сделать объект GAME, где есть свойства - текущие глобальные переменные. Методы - функции
start, 
answer, 
player, 
questions, 
match
getAnswer
match
getAnswer

Game.start()
Game.player.score

Каждый старт score = 0, players = 0

var Game = new Game()...  сделать типо наслодования (у нас будет несколько игр).
Разделить на несколько объектов. Разные игры унаследуют разные методы и свойства

Player отдельный объект. Не пихать функции Player into Game
